version: '3.8'

services:
  db:
    # image: mysql:8.0
    build: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    restart: always
    ports:
      - 3306:3306
    networks:
      - wordpress-network
    deploy:
      resources:
        limits:
          memory: 2048m

  wordpress:
    depends_on:
      - db
    # image: makram89/demo-wp:latest
    build: ./wordpress
    # image: demo-wp
    ports:
      - 8000:80
      - 443:443
    restart: always
    env_file: .env
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
        WORDPRESS_DB_USER: '${MYSQL_USER}'
        WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./wordpress/WordPress/wp-content:/var/www/html/wp-content
    networks:
      - wordpress-network

volumes:
    db_data: {}
    
networks:
  wordpress-network:
    driver: bridge  