FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

COPY ./WordPress /var/www/html/
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +rwx /entrypoint.sh 

RUN apt-get update -q && \
    apt-get install -q -y  php php-cli php-fpm php-mysql apache2 libapache2-mod-php openssl

# Enable required Apache modules
RUN a2enmod rewrite && \
    a2enmod ssl && \
    a2ensite default-ssl

# Generate SSL certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/apache-selfsigned.key \
    -out /etc/ssl/certs/apache-selfsigned.crt \
    -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost"


# Expose ports for HTTP and HTTPS
EXPOSE 80 443

ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["apache2ctl", "-D", "FOREGROUND"]